# -*- coding: utf-8 -*-
"""helloworld.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rkEL9J2qrQ6woHPxQwlX15IXUDIYN7EI
"""

print('Hello wolrddd')

"""hello world"""